### ISSUE TITLE
Appdynamics diskspace monitoring for entire application stack 

### ISSUE THREAD

**Issue by bobbychef64** [Appdynamics/DiskSpaceAlertExtension#2]
Hi thanks for the nice extension , i have a few questions about the extension is it mandatory to provide the admin username  and password  in config file ; when ever i provided the normal user account it's giving error , and if we didn't provide application name in the config its throwing error , I am installing this extension over 1000 nodes . is there any way that we can trigger an alert based on entire application   for the custom metrics.

**Comment by derrekyoung** [comment]
Hi Bobby,

The extension is setup the way it is because it uses the REST API to create a custom event when the disk space crosses a threshold. That API requires the username, password and the application name. It's a requirement of the API, and that API is outside my control. Sorry.

-Derrek

**Comment by bobbychef64** [comment]
Okay thank you for response i am very happy about your reply and understand
how it works.

Thanks
venkat
